server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NextGymDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=teste@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

api.jwt.secret=NextGymApiSecKey2026_x89FqL90A2ZpQ817bVbKmP9q0L1aZr4T